import Hero from "@/components/Hero/Hero";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Bangladesh Easy E-commerce",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>

      {/* Hero Section */}
      <div>
       <Hero />
      </div>
    </div>
  )
}
